function out1 = legendrePoly(x1)
%LEGENDREPOLY
%    OUT1 = LEGENDREPOLY(X1)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    08-Jun-2017 10:20:40

t2 = x1.^2;
t3 = t2.^2;
out1 = reshape([1.0,x1,t2.*(3.0./2.0)-1.0./2.0,x1.*(-3.0./2.0)+t2.*x1.*(5.0./2.0),t2.*(-1.5e1./4.0)+t3.*(3.5e1./8.0)+3.0./8.0,x1.*(1.5e1./8.0)-t2.*x1.*(3.5e1./4.0)+t3.*x1.*(6.3e1./8.0),0.0,1.0,x1.*3.0,t2.*(1.5e1./2.0)-3.0./2.0,x1.*(-1.5e1./2.0)+t2.*x1.*(3.5e1./2.0),t2.*(-1.05e2./4.0)+t3.*(3.15e2./8.0)+1.5e1./8.0],[6,2]);
