function b = nil_legendreP_diff(x)
%NIL_LEGENDREP_DIFF
%    B = NIL_LEGENDREP_DIFF(X)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    09-Jun-2017 14:35:37

t2 = x.^2;
t3 = t2.^2;
b = [1.0,x.*3.0,t2.*(1.5e1./2.0)-3.0./2.0,x.*(-1.5e1./2.0)+t2.*x.*(3.5e1./2.0),t2.*(-1.05e2./4.0)+t3.*(3.15e2./8.0)+1.5e1./8.0,x.*(1.05e2./8.0)-t2.*x.*(3.15e2./4.0)+t3.*x.*(6.93e2./8.0)];
