function out1 = nil_legendreP(x)
%NIL_LEGENDREP
%    OUT1 = NIL_LEGENDREP(X)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    09-Jun-2017 14:34:59

t2 = x.^2;
t3 = t2.^2;
out1 = [x,t2.*(3.0./2.0)-1.0./2.0,x.*(-3.0./2.0)+t2.*x.*(5.0./2.0),t2.*(-1.5e1./4.0)+t3.*(3.5e1./8.0)+3.0./8.0,x.*(1.5e1./8.0)-t2.*x.*(3.5e1./4.0)+t3.*x.*(6.3e1./8.0),t2.*(1.05e2./1.6e1)-t3.*(3.15e2./1.6e1)+t2.*t3.*(2.31e2./1.6e1)-5.0./1.6e1];
